export default {
  CALENDAR: 'CALENDAR',
  PHOTO: 'PHOTO',
  MAP: 'MAP',
  FEELING: 'FEELING',
  TRIP: 'TRIP',
  ACTION: 'ACTION',
  NOTIFICATIONS: 'NOTIFICATIONS',
  INFO: 'INFO',
  FEED: 'FEED',
  SETTINGS: 'SETTINGS',
};
