# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Futupolis' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Futupolis

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'

  pod 'GoogleMaps'

  target 'Futupolis-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  end

  target 'FutupolisTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
